root:
  url: "wss://speedy-nodes-nyc.moralis.io/adc49287d458477aab8d434c/bsc/testnet/ws"
  is-using-ws: true
  is-using-geth: false
  tokens:
    usdt: "0x337610d27c682E347C9cD60BD4b3b107C9d34dDd" # testnet using 18 decimal, faucet by https://testnet.binance.org/faucet-smart